### ISSUE TITLE
Model statistic ordering

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#12]
I appreciate the typical ordering of model stats is:
M WS BS S T W I A LD

In my Mordheim unit cards I re-ordered them to:
M LD I A WS BS S T W

The logic behind this is the order from left to right is much closer to chronological/turn order.

Not in a hurry to have to manually change all the units in these rulebooks, but how do people feel about adopting this stat order?

**Comment by Yther** [comment]
I'm not a huge fan of this idea, but that's because I'm so used to seeing a row of numbers and immediately knowing what they mean. The fact that all the Warhammer books and all the resources we'll be using for the foreseeable future order them in the first way I think will avoid unnecessary confusion. I think it's a fairly major inconvenience for its marginal benefit, though I suppose it doesn't ultimately matter if all the numbers are right. Perhaps have cards/roster options with your numberset as an available option but leave the Mordheim book as is?
