### ISSUE TITLE
Random encounters with monsters/people

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#3]
I think it's worth removing the turn limit on random encounters with creatures. E.g. Skeletons that appear were supposed to only last D3 turns - this seems silly, and is yet another thing to keep track of.

Thought @Yther?

**Comment by Yther** [comment]
I like the turn limit on the Bloodletter since it's a big scary-ass monster that you really have little choice but to run away from, the turn limit means you actually can do. For skeletons it's pretty pointless since they're so weak and slow anyway, but I do like the idea of a big annoying zerg. Perhaps zombies instead of skeletons, no turn limit, but also don't grant xp?
