### ISSUE TITLE
Mordheim vs Hammerheim

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#54]
To discuss

**Comment by Yther** [comment]
I am pretty adamant about this issue. The narrative of the game revolves around the pre-established game universe of Mordheim, and all the races etcetera involved are very clearly from the Warhammer Fantasy universe. I find the argument of protection against litigation weak considering the stats, story, warbands, spells, items, artwork - hell, everything is either original GW content or fanmade GW content used without permission.

If once the project is finished you really want to go over absolutely everything and make it lawyer-friendly then be my guest, I have absolutely no interest in making this project any more public (least of all commercial) than beyond the club. If you would take to take full ownership at that point and make that your thing then you are more than welcome to, but I find it academic in any case to worry about 'what happens if this becomes yuge' before the project is even complete.

**Comment by mcclowes** [comment]
#54
